---
title: "RS Paper"
output: html_document
date: "2023-03-03"
---

```{r}
library(haven)
Data2017 <- read_dta("ZA7500_v5-0-0.dta")
View(Data2017)

Data2017<-na.omit(Data2017)
summary(Data2017)
```

```{r}
Data_cl<-Data2017[c('c_abrv', 'v102', 'v117', 'v174_LR', 'v172')]
Data_Rus<-Data_cl[Data_cl$c_abrv=='RU' & Data_cl$v102>0 & Data_cl$v117>0 & Data_cl$v174_LR>0 & Data_cl$v172>0,]

v102_polor<-Data_Rus$v102 
v117_edsys<-Data_Rus$v117
v174_LR_party<-Data_Rus$v174_LR
v172vote<-Data_Rus$v172
```

```{r}
shapiro.test(v102_polor) #p-value = 1.335e-15 - reject H0
shapiro.test(v117_edsys) #p-value < 2.2e-16 - reject H0
shapiro.test(v174_LR_party) #p-value < 2.2e-16 - reject H0
shapiro.test(v172vote) #p-value < 2.2e-16 - reject H0

var.test(v117_edsys, v102_polor) #p-value < 2.2e-16 - not homogeneous
var.test(v117_edsys, v174_LR_party) #p-value < 2.2e-16 - not homogeneous
var.test(v117_edsys, v172vote) #p-value = 0.04962 - not homogeneous
```

```{r}
cor.test(v117_edsys, v102_polor, method='spearman') #Weak negative relation
cor.test(v117_edsys, v174_LR_party, method='spearman') #Weak, but better that the first, negative relation
cor.test(v117_edsys, v172vote, method='spearman') #Weak, but much better that the first, positive relation
```

```{r}
Regr_Rus<-lm(v117_edsys~v102_polor+v174_LR_party+v172vote)
summary(Regr_Rus)
```

```{r}
library(lmtest)
bptest(Regr_Rus, studentize=FALSE) #the residuals are homoscedastic
```

```{r}
hist(Regr_Rus$residuals,xlab="Residuals",main="")
```

```{r}
vif(Regr_Rus) #multicollinearity is not a major issue in this model
```


```{r}
plot(Regr_Rus)
```

```{r}
library(ggplot2)
a<-ggplot(Regr_Rus) +
aes(x=v102_polor, y=v117_edsys) + geom_point() +
ylab("Trust in educational system") +
xlab("Personal view of political orientation") +
ggtitle("Dependence between variables") +
stat_smooth(method = "lm", col="red")+
theme_bw()

b<-ggplot(Regr_Rus) +
aes(x=v174_LR_party, y=v117_edsys) + geom_point() +
ylab("Trust in educational system") +
xlab("Support for party accordingly party's orientation") +
ggtitle("Dependence between variables") +
stat_smooth(method = "lm", col="red")+
theme_bw()

c<-ggplot(Regr_Rus) +
aes(x=v172vote, y=v117_edsys) + geom_point() +
ylab("Trust in educational system") +
xlab("Level of participation in national level voting") +
ggtitle("Dependence between variables") +
stat_smooth(method = "lm", col="red")+
theme_bw()

library(cowplot)
plot_grid(a,b,c)
```
